config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations], controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'edit', to: 'devise/registrations#edit', as: :edit_user_registration
    put '', to: 'devise/registrations#update', as: :user_registration
  end
  
  root 'home#index'
  resources :contacts, controller: 'contact_us', only: [:new, :create]
  resources :portfolios, only: [:show]
  resources :services, only: [:show]

  namespace :admin do
    resources :dashboards, only: [:index]
    resources :services
    resources :categories, except: [:show]
    resources :portfolios
    resources :teams
    resources :contacts, path: 'contact-us', only: [:index, :show, :destroy, :update] do
      collection do
        patch :mark_all_as_read
      end
      member do
        patch :mark_as
      end      
    end
    resources :settings
    resources :abouts, path: 'about-us'
    resources :technologies, except: [:show]
    resources :client_reviews, path: 'reviews'
  end
end

app/models/service.rb
class Service < ApplicationRecord    
  extend FriendlyId
  friendly_id :title, use: :slugged
  default_scope -> { order(created_at: :desc) }
  
  validates :title, presence: true
  validates :description, presence: true
  enum status: { inactive: 0, active: 1 }  
  has_one_attached :image
  
  validate :image_presence_and_type

  private

  def image_presence_and_type
    if !image.attached?
      errors.add(:image, 'must be attached')
    elsif !image.content_type.in?(%w(image/png image/jpg image/jpeg))
      errors.add(:image, 'must be PNG, JPG or JPEG image)')
    end
  end
end

app/controllers/admin/services_controller.rb
class Admin::ServicesController < Admin::BaseController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  def index
    @services = Service.all
    @services = @services.where('lower(title) like ?', "%#{params[:title].downcase}%") if params[:title].present?
    @services = @services.paginate(page: params[:page], per_page: 12)
  end

  def show; end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)

    if @service.save
      redirect_to admin_services_path, notice: 'Service is Successfully Created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @service.update(service_params)
      redirect_to admin_services_path, notice: 'Service is Successfully Updated.'
    else
      render :edit
    end
  end

  def destroy
    @service.destroy
    redirect_to admin_services_path, notice: 'Service is Successfully Deleted.'
  end

  private

  def set_service
    @service = Service.friendly.find(params[:id])
  end

  def service_params
    params.require(:service).permit(:title, :description, :image, :status)
  end
end
  

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def show
    @service = Service.friendly.find(params[:id])
    @setting = Setting.where(status: 'active').take
    @services = Service.where(status: 'active')
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/admin/services/_form.html.erb
<div class="text-center">
  <h1 class="h4 font-weight-bold text-gray-900 mb-4">
    <i class="fa fa-server"></i> Service</h1>
</div>
<%= form_with(model: [ :admin, service ], local: true) do |form| %>
  <% if service.errors.any? %>
    <div  class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <p><i class="fa fa-exclamation"></i> <%= pluralize(service.errors.count, "error") %>: Unable to save changes.</p>
      <ul>
        <% service.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.text_field :title, class:'form-control form-control-user', required: true, placeholder: 'Enter Title...' %>
  </div>
  <div class="form-group">
    <%= form.text_area :description, class:'form-control form-control-user tinymce', placeholder:'Add Description' %>
  </div>
  <div class="form-group">
    <%= form.file_field :image, class:'form-control form-control-user' %>
    <% if @service.image.attached? %>
      <p class="mt-2">Image is attached</p>
    <% else %>
      <p class="mt-2">No Image attached</p>
    <%end%>
  </div>
  <div class="form-group">
    <%= form.select :status, Service.statuses.keys.to_a.map {|status| [status.humanize, status]},{include_blank: 'Select Status'}, class:'form-control form-control-user', required: true %>
  </div>    
  <div class="button-group py-2 d-flex justify-content-between align-items-center">                                                                                                                                                             
    <a href="<%= admin_services_path %>" class="btn btn-dark btn-icon-split">
      <span class="icon text-white"><i class="fas fa-arrow-left"></i></span>
      <span class="text">Back</span>
    </a>
    <%= form.submit class: 'btn btn-dark' %>
  </div>
<%end%>

app/views/admin/services/_lists.html.erb
<table class="services-data-table table table-bordered" id="dataTable" width="100%" cellspacing="0">
  <thead>
    <tr>
      <th>Sr.</th>
      <th>Title</th>
      <th>Status</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% services.each_with_index do |service, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%=service.title%></td>
        <td>
          <% if service.status == 'inactive' %>
            <div class="custom-control custom-switch">
              <input type="checkbox" class="custom-control-input" id="customSwitches ">
              <label class="custom-control-label" for="customSwitches"></label>
            </div>
          <%elsif service.status == 'active' %>
            <div class="custom-control custom-switch">
              <input type="checkbox" class="custom-control-input" id="customSwitches " checked>
              <label class="custom-control-label" for="customSwitches"></label>
            </div>
          <%end%>
        </td>
        <td>                    
          <%= link_to admin_service_path(service), title:"View", class:'btn btn-success' do %>
            <i class="fas fa-eye"></i>
          <%end%>                     
          <%= link_to edit_admin_service_path(service), title:"Edit", class:'btn btn-secondary' do %>
            <i class="fas fa-edit"></i>
          <%end%>
          <%= link_to admin_service_path(service), title:"Delete", method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' do %>
            <i class="fa fa-trash"></i>
          <%end%>
          <%= link_to service_path(service), title:"View in Website", target:'_blank', class:'btn btn-success' do %>
            <i class="fas fa-globe"></i>
          <%end%>                      
        </td>
      </tr>
    <%end%>
  </tbody>
</table>
<div class="dataTables_paginate paging_simple_numbers float-right" id="dataTable_paginate">
  <%= will_paginate services, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

app/views/admin/services/edit.html.erb
<%= render 'admin/shared/form' do %>
  <%= render 'form', service: @service %>
<% end %>

app/views/admin/services/index.html.erb
<div class="container-fluid">
  <div class="card shadow mb-4">
    <div class="card-header py-3 d-flex justify-content-between align-items-center">
      <div class="d-flex align-items-center text-mute">
        <i class="fa fa-server h3 mr-1"></i>
        <h3 class="font-weight-bold">Services</h3>
      </div>   
      <a href="<%= new_admin_service_path %>" class="btn btn-dark btn-icon-split">
        <span class="icon text-white"><i class="fas fa-plus"></i></span>
        <span class="text">New Service</span>
      </a>
    </div>
    <div class="card-body">
      <%= render 'admin/shared/filters' %>
      <div class="table-responsive services-table">
        <%= render 'lists', services: @services %>
      </div>
    </div>
  </div>
</div>

app/views/admin/services/index.js.erb
$('.services-table').html('<%= j(render 'lists', services: @services)%>');
$('.services-data-table').DataTable({
  searching: false,
  lengthChange: false,
  paging: false
});

app/views/admin/services/new.html.erb
<%= render 'admin/shared/form' do %>
  <%= render 'form', service: @service %>
<% end %>

app/views/admin/services/show.html.erb
<div class="container">
  <div class="card mb-3">
    <div class="card-header py-3 d-flex justify-content-between align-items-center">
      <h4 class="m-0 font-weight-bold text-mute"><i class="fa fa-server"></i> Service</h4>
      <p class="card-text">
        <%= content_tag :i, '', class: "fas fa-#{(@service.status == 'active') ? 'check-circle text-success' : 'pause-circle text-danger'}" %>
        <span class="font-weight-bold text-capitalize <%= @service.status == 'inactive' ? 'text-danger' : 'text-success' %>">
          <%= @service.status %>
        </span>
      </p>      
    </div>
    <div class="row g-0">
      <div class="col-md-4">
        <div class="card-body">
          <%= image_tag @service.image, class:'card-img' if @service.image.attached? %>        
        </div>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title text-dark"><i class="fa fa-clipboard"></i> Service Name</h5>
          <p class="card-text"><%= @service.title %></p>                   
          <h5 class="card-title text-dark"><i class="fa fa-align-left"></i> Description</h5>
          <p class="card-text"><%= raw @service.description %></p>
        </div>
      </div>     
    </div>
    <div class="card-header py-3">
      <a href="<%= admin_services_path %>" class="btn btn-dark btn-icon-split">
        <span class="icon text-white"><i class="fas fa-arrow-left"></i></span>
        <span class="text">Back</span>
      </a>
    </div>
  </div>
</div>