config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations], controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'edit', to: 'devise/registrations#edit', as: :edit_user_registration
    put '', to: 'devise/registrations#update', as: :user_registration
  end
  
  root 'home#index'
  resources :contacts, controller: 'contact_us', only: [:new, :create]
  resources :portfolios, only: [:show]
  resources :services, only: [:show]

  namespace :admin do
    resources :dashboards, only: [:index]
    resources :services
    resources :categories, except: [:show]
    resources :portfolios
    resources :teams
    resources :contacts, path: 'contact-us', only: [:index, :show, :destroy, :update] do
      collection do
        patch :mark_all_as_read
      end
      member do
        patch :mark_as
      end      
    end
    resources :settings
    resources :abouts, path: 'about-us'
    resources :technologies, except: [:show]
    resources :client_reviews, path: 'reviews'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index 
    @about = About.where(status: 'active').take
		@categories = Category.all
		@technologies = Technology.where(status: 'active')
		@services = Service.where(status: 'active')
		@portfolios = Portfolio.where(status: 'active')
		@reviews = ClientReview.where(status: 'active')
		@teams = Team.where(status: 'active')
    @setting = Setting.where(status: 'active').take
		@contacts = Contact.all
		@contact = Contact.new
	end
end

app/views/home/shared/_about.html.erb
<section id="about" class="about">
  <div class="container" data-aos="fade-up">
    <div class="row">
      <div class="col-lg-6 order-1 order-lg-2" data-aos="fade-left" data-aos-delay="100">
        <%= image_tag @about.image, class:'img-fluid', alt:'About Image' if @about.image.attached? %>
      </div>
      <div class="col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content" data-aos="fade-right" data-aos-delay="100">
        <h3><%= @about.title%></h3>
        <p class="fst-italic">
          <%= raw @about.description%>
        </p>
      </div>
    </div>
  </div>
</section>

app/views/home/shared/_client-reviews.html.erb
<section id="testimonials" class="testimonials">
  <div class="container" data-aos="zoom-in">
    <div class="testimonials-slider swiper" data-aos="fade-up" data-aos-delay="100">
      <div class="swiper-wrapper">
        <% @reviews.each do |review| %>
          <div class="swiper-slide">
            <div class="testimonial-item">
              <%= image_tag review.image, class:'testimonial-img', alt:'Client Image' if review.image.attached? %>
              <h3><%= review.name %></h3>
              <h4><%= review.designation %></h4>
              <p>
                <i class="ri-double-quotes-l quote-icon-left"></i>
                <%= review.review %>
                <i class="ri-double-quotes-r quote-icon-right"></i>
              </p>
            </div>
          </div>
        <%end%>
      </div>
      <div class="swiper-pagination"></div>
    </div>
  </div>
</section>

app/views/home/shared/_contact.html.erb
<section id="contact" class="contact">
  <div class="container" data-aos="fade-up">
    <div class="section-title">
      <h2>Contact</h2>
      <p>Contact Us</p>
    </div>
    <div>
      <iframe style="border:0; width: 100%; height: 270px;" src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12097.433213460943!2d-74.0062269!3d40.7101282!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb89d1fe6bc499443!2sDowntown+Conference+Center!5e0!3m2!1smk!2sbg!4v1539943755621" frameborder="0" allowfullscreen></iframe>
    </div>
    <div class="row mt-5">
      <div class="col-lg-4">
        <div class="info">
          <div class="address">
            <i class="ri-map-pin-line"></i>
            <h4>Location:</h4>
            <p><%= @setting.location %></p>
          </div>
          <div class="email">
            <i class="ri-mail-line"></i>
            <h4>Email:</h4>
            <p><%= @setting.email %></p>
          </div>
          <div class="phone">
            <i class="ri-smartphone-line"></i>
            <h4>Call:</h4>
            <p><%= @setting.phone_number %></p>
          </div>
        </div>
      </div>
      <div class="col-lg-8 mt-5 mt-lg-0">
        <%= render 'contact_us/contact_form'%>
      </div>
    </div>
  </div>
</section>

app/views/home/shared/_cta.html.erb
<section id="cta" class="cta">
  <div class="container" data-aos="zoom-in">
    <div class="text-center">
      <h3>Call To Action</h3>
      <p> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <a class="cta-btn" href="#">Call To Action</a>
    </div>
  </div>
</section>

app/views/home/shared/_footer.html.erb
<footer id="footer">
  <div class="footer-top">
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-6">
          <div class="footer-info">
            <h3>BK<span>.</span></h3>
            <p>
              <%= @setting.location %><br><br>
              <strong>Phone:</strong> <%= @setting.phone_number%><br>
              <strong>Email:</strong> <%= @setting.email%><br>
            </p>
            <div class="social-links mt-3">
              <% if @setting.social_urls['twitter_url'].present? %>
                <a href="<%= @setting.social_urls['twitter_url'] %>" target="_blank" class="twitter"><i class="ri-twitter-fill"></i></a>
              <% end %>
              <% if @setting.social_urls['facebook_url'].present? %>
                <a href="<%= @setting.social_urls['facebook_url'] %>" target="_blank" class="facebook"><i class="ri-facebook-fill"></i></a>
              <% end %>
              <% if @setting.social_urls['instagram_url'].present? %>
                <a href="<%= @setting.social_urls['instagram_url'] %>" target="_blank" class="instagram"><i class="ri-instagram-line"></i></a>
              <% end %>
              <% if @setting.social_urls['skype_url'].present? %>
                <a href="<%= @setting.social_urls['skype_url'] %>" target="_blank" class="google-plus"><i class="ri-skype-fill"></i></a>
              <% end %>
              <% if @setting.social_urls['linkedin_url'].present? %>
                <a href="<%= @setting.social_urls['linkedin_url'] %>" target="_blank" class="linkedin"><i class="ri-linkedin-box-fill"></i></a>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-lg-2 col-md-6 footer-links">
          <h4>Useful Links</h4>
          <ul>
            <li><i class="ri-arrow-right-s-line"></i> <a href="#">Home</a></li>
            <li><i class="ri-arrow-right-s-line"></i> <a href="#about">About us</a></li>
            <li><i class="ri-arrow-right-s-line"></i> <a href="#services">Services</a></li>
            <li><i class="ri-arrow-right-s-line"></i> <a href="#portfolio">Portfolios</a></li>
            <li><i class="ri-arrow-right-s-line"></i> <a href="#team">Teams</a></li>
          </ul>
        </div>
        <div class="col-lg-3 col-md-6 footer-links">
          <h4>Our Services</h4>
          <ul>
            <% @services.each_with_index do |service, index| %>
              <% if index < 5 %>
                <li><i class="ri-arrow-right-s-line"></i> 
                  <a href="<%= service_path(service)%>"><%= service.title %></a>
                </li>
              <%end%>
            <%end%>
          </ul>
        </div>
        <div class="col-lg-4 col-md-6 footer-newsletter">
          <h4>Our Newsletter</h4>
          <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
          <form action="" method="post">
            <input type="email" name="email"><input type="submit" value="Subscribe">
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <%= raw @setting.copyright if @setting.copyright.present? %>
  </div>
</footer>
<%# <div id="preloader"></div> %>
<a href="#" class="back-to-top d-flex align-items-center justify-content-center">
  <i class="ri-arrow-up-line"></i>
</a>

app/views/home/shared/_header.html.erb
<header id="header" class="fixed-top ">
  <div class="container d-flex align-items-center justify-content-lg-between">
    <h1 class="logo me-auto me-lg-0"><a href="index.html">BK<span>.</span></a></h1>
    <nav id="navbar" class="navbar order-last order-lg-0">
      <ul>
        <li><a class="nav-link scrollto active" href="#hero">Home</a></li>
        <li><a class="nav-link scrollto" href="#about">About</a></li>
        <li><a class="nav-link scrollto" href="#services">Services</a></li>
        <li><a class="nav-link scrollto " href="#portfolio">Portfolio</a></li>
        <li><a class="nav-link scrollto" href="#team">Team</a></li>
        <li><a class="nav-link scrollto" href="#contact">Contact</a></li>
      </ul>
      <i class="fa fa-bars mobile-nav-toggle"></i>
    </nav>
    <div>
      <%= link_to 'Dashboard', admin_dashboards_path, class:'get-started-btn scrollto', target: "_blank" if user_signed_in? %>
      <a href="#about" class="get-started-btn scrollto">Get Started</a>
    </div>
  </div>
</header>

app/views/home/shared/_hero-section.html.erb
<section id="hero" class="d-flex align-items-center justify-content-center">
  <div class="container" data-aos="fade-up">
    <div class="row justify-content-center" data-aos="fade-up" data-aos-delay="150">
      <div class="col-xl-6 col-lg-8">
          <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
          <% end %>
        <h1>Powerful Digital Solutions With Bk<span>.</span></h1>
        <h2>We are team of talented digital marketers</h2>
      </div>
    </div>
    <div class="row gy-4 mt-5 justify-content-center" data-aos="zoom-in" data-aos-delay="250">
      <div class="col-xl-2 col-md-4">
        <div class="icon-box">
          <i class="ri-store-line"></i>
          <h3><a href="">Lorem Ipsum</a></h3>
        </div>
      </div>
      <div class="col-xl-2 col-md-4">
        <div class="icon-box">
          <i class="ri-bar-chart-box-line"></i>
          <h3><a href="">Dolor Sitema</a></h3>
        </div>
      </div>
      <div class="col-xl-2 col-md-4">
        <div class="icon-box">
          <i class="ri-calendar-todo-line"></i>
          <h3><a href="">Sedare Perspiciatis</a></h3>
        </div>
      </div>
      <div class="col-xl-2 col-md-4">
        <div class="icon-box">
          <i class="ri-paint-brush-line"></i>
          <h3><a href="">Magni Dolores</a></h3>
        </div>
      </div>
      <div class="col-xl-2 col-md-4">
        <div class="icon-box">
          <i class="ri-database-2-line"></i>
          <h3><a href="">Nemos Enimade</a></h3>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/shared/_portfolio.html.erb
<section id="portfolio" class="portfolio">
  <div class="container" data-aos="fade-up">
    <div class="section-title">
      <h2>Portfolio</h2>
      <p>Check our Portfolio</p>
    </div>
    <div class="row" data-aos="fade-up" data-aos-delay="100">
      <div class="col-lg-12 d-flex justify-content-center">
        <ul id="portfolio-flters">
          <li data-filter="*" class="filter-active">All</li>
          <% @categories.each do |category|%>
            <li data-filter=".<%= category.title.parameterize %>"><%= category.title %></li>
          <%end%>
        </ul>
      </div>
    </div>
    <div class="row portfolio-container" data-aos="fade-up" data-aos-delay="200">
      <% @portfolios.each do |portfolio|%>
        <div class="col-lg-4 col-md-6 portfolio-item filter-app <%= portfolio.category.title.parameterize %>">
          <div class="portfolio-wrap">
            <%= image_tag portfolio.images.first, class:'img-fluid', alt:'Portfolio Image' if portfolio.images.attached? %>
            <div class="portfolio-info">
              <h4><%= portfolio.title %></h4>
              <p><%= portfolio.category.title %></p>
              <div class="portfolio-links">
                <% if portfolio.images.attached? %>
                  <% portfolio.images.each_with_index do |image, index| %>
                    <a href="<%= url_for(image) %>" data-gallery="portfolioGallery" class="portfolio-lightbox" title="<%= portfolio.title %>">
                      <% if index == 0 %>
                        <i class="ri-add-line"></i>
                      <%end%>
                    </a>
                  <% end %>
                <% end %>
                <a href="<%= portfolio_path(portfolio) %>" title="More Details"><i class="ri-links-fill"></i></a>
              </div>
            </div>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</section>

app/views/home/shared/_services.html.erb
<section id="services" class="services">
  <div class="container" data-aos="fade-up">
    <div class="section-title">
      <h2>Services</h2>
      <p>Check our Services</p>
    </div>
    <div class="row">
      <% @services.each do |service| %>
        <div class="col-lg-4 col-md-6 d-flex align-items-stretch" data-aos="zoom-in" data-aos-delay="100">
          <div class="icon-box">
            <div class="icon">
              <%= image_tag service.image, class:'img-fluid' if service.image.attached? %>
            </div>
            <h4><a href="<%= service_path(service) %>"><%= service.title %></a></h4>
            <p><%= raw service.description %></p>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</section>

app/views/home/shared/_team.html.erb
<section id="team" class="team">
  <div class="container" data-aos="fade-up">
    <div class="section-title">
      <h2>Team</h2>
      <p>Check our Team</p>
    </div>
    <div class="row">
      <% @teams.each do |team| %>
        <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
          <div class="member" data-aos="fade-up" data-aos-delay="100">
            <div class="member-img">
              <%= image_tag team.image, class:'img-fluid', alt:'Team Image' if team.image.attached? %>
              <div class="social">
                <a href="<%= team.twitter_url %>"><i class="ri-twitter-fill"></i></a>
                <a href="<%= team.facebook_url %>"><i class="ri-facebook-circle-fill"></i></a>
                <a href="<%= team.instagram_url %>"><i class="ri-instagram-line"></i></a>
                <a href="<%= team.linkedin_url %>"><i class="ri-linkedin-box-fill"></i></a>
              </div>
            </div>
            <div class="member-info">
              <h4><%= team.name %></h4>
              <span><%= team.designation %></span>
            </div>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</section>

app/views/home/shared/_technology.html.erb
<section id="clients" class="clients">
  <div class="container" data-aos="zoom-in">
    <div class="clients-slider swiper">
      <div class="swiper-wrapper align-items-center">
        <% @technologies.each do |technology| %>
          <div class="swiper-slide">
            <%= image_tag technology.image, class:'img-fluid', alt:'Technology Image' if technology.image.attached? %>
          </div>
        <%end%>
      </div>
      <div class="swiper-pagination"></div>
    </div>
  </div>
</section>